package com.example.demo.Controller;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;

import com.example.demo.dao.DAO_Empolyee;
import com.example.demo.dao.DAO_Guest;
import com.example.demo.dao.DAO_RoomType;
import com.example.demo.entity.Empolyee;
import com.example.demo.entity.Guest;
import com.example.demo.entity.RoomType;
import com.example.demo.service.MailerService;

@Controller
public class Controller_Admin {
	@Autowired
	DAO_Guest dao;
	@Autowired
	DAO_RoomType serviceRoomType;
	@Autowired
	JavaMailSender sender;

	@Autowired
	MailerService mailer;

	@GetMapping({ "admin", "admin/home/index" })
	public String admin(Model model) {
		model.addAttribute("title", "About");
		return "redirect:/admin/index.html";
	}

	@PostMapping("admin/home/index")
	public String sendEvent(Model model, @RequestParam("title") String title,
			@RequestParam("description") String description) {
		List<Guest> list = dao.findAll();
		List<RoomType> items = serviceRoomType.findBySale();
		String test = "";
		for (RoomType i : items) {
			test =  "                                <table class=\"es-content-body\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\""
					+ "                                    bgcolor=\"#ffffff\" align=\"center\">"
					+ "                                    <tr>"
					+ "                                        <td class=\"es-p20\" align=\"left\">"
					+ "                                            <!--[if mso]><table width=\"560\" cellpadding=\"0\" cellspacing=\"0\"><tr><td width=\"194\"><![endif]-->"
					+ "                                            <table class=\"es-left\" cellspacing=\"0\" cellpadding=\"0\" align=\"left\">"
					+ "                                                <tr>"
					+ "                                                    <td class=\"es-m-p20b\" width=\"174\" align=\"left\">"
					+ "                                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\""
					+ "                                                            role=\"presentation\">"
					+ "                                                            <tr>"
					+ "                                                                <td align=\"center\" style=\"font-size:0\"><a"
					+ "                                                                        target=\"_blank\""
					+ "                                                                        href=\"https://viewstripo.email\"><img"
					+ "                                                                            class=\"adapt-img\""
					+ "                                                                            src=\"https://ylizcr.stripocdn.email/content/guids/CABINET_dd6c2fc75280628bbfba9fc299ddf05b/images/70461506325852603.jpg\""
					+ "                                                                            width=\"135\""
					+ "                                                                            height=\"135\""
					+ "                                                                            layout=\"responsive\"></a></td>"
					+ "                                                            </tr>" +

					"                                                            <tr >"
					+ "                                                                <td class=\"es-p20t\" align=\"enter\">"
					+ "                       <h4 style=\"color: #333333; text-align:center; font-size:19px;\">"
					+ i.getName() + " ("+ i.getSale() + "%)" + "</h4>"
					+ "                                                                </td>"
					+ "                                                            </tr>"
					+ "                                                            <tr>"
					+ "                                                                <td class=\"es-p10t\" align=\"center\">"
					+ "                                                                    <p style=\"color: #666666;line-height: 150%\"><span"
					+ "                                                                            style=\"color: #a9a9a9;font-size: 16px\"><s>$<span"
					+ "                                                                                    class=\"old-price\">"
					+ i.getPrice() + "</span></s></span><span"
					+ "                                                                            style=\"color: #faa41d;font-size: 24px\"><span"
					+ "                                                                                style=\"font-size:18px\">$</span><span"
					+ "                                                                                class=\"price\">"
					+ i.getPrice() * ((100 - i.getSale()) / 100) + "</span></span><span"
					+ "                                                                            style=\"font-size:12px\">per night</span></p>"
					+ "                                                                </td>"
					+ "                                                            </tr>"
					+ "                                                            <tr>"
					+ "                                                                <td class=\"es-p5t\" align=\"center\">"
					+ "                                                                    <p style=\"color: #666666;line-height: 150%\"><span"
					+ "                                                                            class=\"product-description\""
					+ "                                                                            style=\"font-size: 12px;line-height: 18px\">"
					+ i.getRoomdesc() + "" + "</span></p>"
					+ "                                                                </td>"
					+ "                                                            </tr>"
					+ "                                                            <tr>"
					+ "                                                                <td class=\"es-p10t es-p15b\" align=\"center\""
					+ "                                                                    style=\"font-size:0\"><a target=\"_blank\""
					+ "                                                                        href=\"https://viewstripo.email\"><img"
					+ "                                                                            src=\"https://ylizcr.stripocdn.email/content/guids/CABINET_9f0c7ef4cb9cbe15f984af25f0f3e1fa/images/20051506326591508.png\""
					+ "                                                                            alt width=\"70\" height=\"12\"></a>"
					+ "                                                                </td>"
					+ "                                                            </tr>"
					+ "                                                            <tr>"
					+ "                                                                <td class=\"es-p5t es-p15b\" align=\"center\"><span"
					+ "                                                                        class=\"es-button-border\""
					+ "                                                                        style=\"border-radius: 0px;border-style: solid;background: #14141e ;border-width: 0px;border-color: #ffffff\"><a"
					+ "                                                                            href=\"http://localhost:8080/home/index/rooms/detail-room/"
					+ i.getType() + "\""
					+ "                                                                            class=\"es-button es-button-1\""
					+ "                                                                            target=\"_blank\""
					+ "                                                                            style=\"border-radius: 0px;color: #efefef;background: #14141e ;border-color: #14141e;border-width: 10px 20px\">Book"
					+ "                                                                            now</a></span></td>"
					+ "                                                            </tr>"
					+ "                                                        </table>"
					+ "                                                    </td>"
					+ "                                                    <td class=\"es-hidden\" width=\"20\"></td>"
					+ "                                                </tr>"
					+ "                                            </table> ";
			System.out.println(test);

		}
		for (int i = 0; i < list.size(); i++) {
			try {
				System.out.println(list.get(i).getEmail());
				mailer.send(list.get(i).getEmail(), "GOLDEN HOTEL", "<!doctype html>" + "<html email data-css-strict >"
						+ "" + "<head>" + "<script\r\n"
						+ "	src=\"https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.8.2/angular.min.js\"\r\n"
						+ "	integrity=\"sha512-7oYXeK0OxTFxndh0erL8FsjGvrl2VMDor6fVqzlLGfwOQQqTbYsGPv4ZZ15QHfSk80doyaM0ZJdvkyDcVO7KFA==\"\r\n"
						+ "	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>"
						+ "    <meta charset=\"utf-8\">" + "    <style amp4email-boilerplate>" + "        body {"
						+ "            visibility: hidden" + "        }" + "    </style>"
						+ "    <script async src=\"https://cdn.ampproject.org/v0.js\"></script>"
						+ "    <style amp-custom>" + "        .es-desk-hidden {" + "            display: none;"
						+ "            float: left;" + "            overflow: hidden;" + "            width: 0;"
						+ "            max-height: 0;" + "            line-height: 0;" + "        }" + ""
						+ "        s {" + "            text-decoration: line-through;" + "        }" + ""
						+ "        body {" + "            width: 100%;" + "        }" + "" + "        body {"
						+ "            font-family: \"arial\", \"helvetica neue\", \"helvetica\", \"sans-serif\";"
						+ "        }" + "" + "        table {" + "            border-collapse: collapse;"
						+ "            border-spacing: 0px;" + "        }" + "" + "        table td," + "        html,"
						+ "        body," + "        .es-wrapper {" + "            padding: 0;"
						+ "            Margin: 0;" + "        }" + "" + "        .es-content," + "        .es-header,"
						+ "        .es-footer {" + "            table-layout: fixed;" + "            width: 100%;"
						+ "        }" + "" + "        p," + "        hr {" + "            Margin: 0;" + "        }" + ""
						+ "        h1," + "        h2," + "        h3," + "        h4," + "        h5 {"
						+ "            Margin: 0;" + "            line-height: 120%;"
						+ "            font-family: \"arial\", \"helvetica neue\", \"helvetica\", \"sans-serif\";"
						+ "        }" + "" + "        .es-left {" + "            float: left;" + "        }" + ""
						+ "        .es-right {" + "            float: right;" + "        }" + "" + "        .es-p5 {"
						+ "            padding: 5px;" + "        }" + "" + "        .es-p5t {"
						+ "            padding-top: 5px;" + "        }" + "" + "        .es-p5b {"
						+ "            padding-bottom: 5px;" + "        }" + "" + "        .es-p5l {"
						+ "            padding-left: 5px;" + "        }" + "" + "        .es-p5r {"
						+ "            padding-right: 5px;" + "        }" + "" + "        .es-p10 {"
						+ "            padding: 10px;" + "        }" + "" + "        .es-p10t {"
						+ "            padding-top: 10px;" + "        }" + "" + "        .es-p10b {"
						+ "            padding-bottom: 10px;" + "        }" + "" + "        .es-p10l {"
						+ "            padding-left: 10px;" + "        }" + "" + "        .es-p10r {"
						+ "            padding-right: 10px;" + "        }" + "" + "        .es-p15 {"
						+ "            padding: 15px;" + "        }" + "" + "        .es-p15t {"
						+ "            padding-top: 15px;" + "        }" + "" + "        .es-p15b {"
						+ "            padding-bottom: 15px;" + "        }" + "" + "        .es-p15l {"
						+ "            padding-left: 15px;" + "        }" + "" + "        .es-p15r {"
						+ "            padding-right: 15px;" + "        }" + "" + "        .es-p20 {"
						+ "            padding: 20px;" + "        }" + "" + "        .es-p20t {"
						+ "            padding-top: 20px;" + "        }" + "" + "        .es-p20b {"
						+ "            padding-bottom: 20px;" + "        }" + "" + "        .es-p20l {"
						+ "            padding-left: 20px;" + "        }" + "" + "        .es-p20r {"
						+ "            padding-right: 20px;" + "        }" + "" + "        .es-p25 {"
						+ "            padding: 25px;" + "        }" + "" + "        .es-p25t {"
						+ "            padding-top: 25px;" + "        }" + "" + "        .es-p25b {"
						+ "            padding-bottom: 25px;" + "        }" + "" + "        .es-p25l {"
						+ "            padding-left: 25px;" + "        }" + "" + "        .es-p25r {"
						+ "            padding-right: 25px;" + "        }" + "" + "        .es-p30 {"
						+ "            padding: 30px;" + "        }" + "" + "        .es-p30t {"
						+ "            padding-top: 30px;" + "        }" + "" + "        .es-p30b {"
						+ "            padding-bottom: 30px;" + "        }" + "" + "        .es-p30l {"
						+ "            padding-left: 30px;" + "        }" + "" + "        .es-p30r {"
						+ "            padding-right: 30px;" + "        }" + "" + "        .es-p35 {"
						+ "            padding: 35px;" + "        }" + "" + "        .es-p35t {"
						+ "            padding-top: 35px;" + "        }" + "" + "        .es-p35b {"
						+ "            padding-bottom: 35px;" + "        }" + "" + "        .es-p35l {"
						+ "            padding-left: 35px;" + "        }" + "" + "        .es-p35r {"
						+ "            padding-right: 35px;" + "        }" + "" + "        .es-p40 {"
						+ "            padding: 40px;" + "        }" + "" + "        .es-p40t {"
						+ "            padding-top: 40px;" + "        }" + "" + "        .es-p40b {"
						+ "            padding-bottom: 40px;" + "        }" + "" + "        .es-p40l {"
						+ "            padding-left: 40px;" + "        }" + "" + "        .es-p40r {"
						+ "            padding-right: 40px;" + "        }" + "" + "        .es-menu td {"
						+ "            border: 0;" + "        }" + "" + "        a {"
						+ "            text-decoration: underline;" + "        }" + "" + "        p," + "        ul li,"
						+ "        ol li {"
						+ "            font-family: \"arial\", \"helvetica neue\", \"helvetica\", \"sans-serif\";"
						+ "            line-height: 150%;" + "        }" + "" + "        ul li," + "        ol li {"
						+ "            Margin-bottom: 15px;" + "            margin-left: 0;" + "        }" + ""
						+ "        .es-menu td a {" + "            text-decoration: none;"
						+ "            display: block;"
						+ "            font-family: \"arial\", \"helvetica neue\", \"helvetica\", \"sans-serif\";"
						+ "        }" + "" + "        .es-menu img," + "        .es-button img {"
						+ "            vertical-align: middle;" + "        }" + "" + "        .es-wrapper {"
						+ "            width: 100%;" + "            height: 100%;" + "        }" + ""
						+ "        .es-wrapper-color," + "        .es-wrapper {"
						+ "            background-color: #F6F6F6;" + "        }" + "" + "        .es-header {"
						+ "            background-color: transparent;" + "        }" + "" + "        .es-header-body {"
						+ "            background-color: #FFFFFF;" + "        }" + "" + "        .es-header-body p,"
						+ "        .es-header-body ul li," + "        .es-header-body ol li {"
						+ "            color: #999999;" + "            font-size: 14px;" + "        }" + ""
						+ "        .es-header-body a {" + "            color: #999999;" + "            font-size: 14px;"
						+ "        }" + "" + "        .es-content-body {" + "            background-color: #FFFFFF;"
						+ "        }" + "" + "        .es-content-body p," + "        .es-content-body ul li,"
						+ "        .es-content-body ol li {" + "            color: #333333;"
						+ "            font-size: 14px;" + "        }" + "" + "        .es-content-body a {"
						+ "            color: #FAA41D;" + "            font-size: 14px;" + "        }" + ""
						+ "        .es-footer {" + "            background-color: transparent;" + "        }" + ""
						+ "        .es-footer-body {" + "            background-color: #EFEFEF;" + "        }" + ""
						+ "        .es-footer-body p," + "        .es-footer-body ul li,"
						+ "        .es-footer-body ol li {" + "            color: #666666;"
						+ "            font-size: 14px;" + "        }" + "" + "        .es-footer-body a {"
						+ "            color: #666666;" + "            font-size: 14px;" + "        }" + ""
						+ "        .es-infoblock," + "        .es-infoblock p," + "        .es-infoblock ul li,"
						+ "        .es-infoblock ol li {" + "            line-height: 120%;"
						+ "            font-size: 12px;" + "            color: #999999;" + "        }" + ""
						+ "        .es-infoblock a {" + "            font-size: 12px;" + "            color: #999999;"
						+ "        }" + "" + "        h1 {" + "            font-size: 30px;"
						+ "            font-style: normal;" + "            font-weight: normal;"
						+ "            color: #333333;" + "        }" + "" + "        h2 {"
						+ "            font-size: 24px;" + "            font-style: normal;"
						+ "            font-weight: normal;" + "            color: #333333;" + "        }" + ""
						+ "        h3 {" + "            font-size: 20px;" + "            font-style: normal;"
						+ "            font-weight: bold;" + "            color: #333333;" + "        }" + ""
						+ "        .es-header-body h1 a," + "        .es-content-body h1 a,"
						+ "        .es-footer-body h1 a {" + "            font-size: 30px;" + "        }" + ""
						+ "        .es-header-body h2 a," + "        .es-content-body h2 a,"
						+ "        .es-footer-body h2 a {" + "            font-size: 24px;" + "        }" + ""
						+ "        .es-header-body h3 a," + "        .es-content-body h3 a,"
						+ "        .es-footer-body h3 a {" + "            font-size: 20px;" + "        }" + ""
						+ "        a.es-button," + "        button.es-button {" + "            border-style: solid;"
						+ "            border-color: #14141E;" + "            border-width: 10px 20px 10px 20px;"
						+ "            display: inline-block;" + "            background: #14141E;"
						+ "            border-radius: 0px;" + "            font-size: 18px;"
						+ "            font-family: \"arial\", \"helvetica neue\", \"helvetica\", \"sans-serif\";"
						+ "            font-weight: normal;" + "            font-style: normal;"
						+ "            line-height: 120%;" + "            color: #EFEFEF;"
						+ "            text-decoration: none;" + "            width: auto;"
						+ "            text-align: center;" + "        }" + "" + "        .es-button-border {"
						+ "            border-style: solid solid solid solid;"
						+ "            border-color: #14141E #14141E #14141E #14141E;"
						+ "            background: #2CB543;" + "            border-width: 0px 0px 0px 0px;"
						+ "            display: inline-block;" + "            border-radius: 0px;"
						+ "            width: auto;" + "        }" + ""
						+ "        @media only screen and (max-width:600px) {" + "" + "            p,"
						+ "            ul li," + "            ol li," + "            a {"
						+ "                line-height: 150%" + "            }" + "" + "            h1,"
						+ "            h2," + "            h3," + "            h1 a," + "            h2 a,"
						+ "            h3 a {" + "                line-height: 120%" + "            }" + ""
						+ "            h1 {" + "                font-size: 30px;" + "                text-align: center"
						+ "            }" + "" + "            h2 {" + "                font-size: 26px;"
						+ "                text-align: center" + "            }" + "" + "            h3 {"
						+ "                font-size: 20px;" + "                text-align: center" + "            }"
						+ "" + "            .es-header-body h1 a," + "            .es-content-body h1 a,"
						+ "            .es-footer-body h1 a {" + "                font-size: 30px" + "            }"
						+ "" + "            .es-header-body h2 a," + "            .es-content-body h2 a,"
						+ "            .es-footer-body h2 a {" + "                font-size: 26px" + "            }"
						+ "" + "            .es-header-body h3 a," + "            .es-content-body h3 a,"
						+ "            .es-footer-body h3 a {" + "                font-size: 20px" + "            }"
						+ "" + "            .es-menu td a {" + "                font-size: 14px" + "            }" + ""
						+ "            .es-header-body p," + "            .es-header-body ul li,"
						+ "            .es-header-body ol li," + "            .es-header-body a {"
						+ "                font-size: 16px" + "            }" + "" + "            .es-content-body p,"
						+ "            .es-content-body ul li," + "            .es-content-body ol li,"
						+ "            .es-content-body a {" + "                font-size: 14px" + "            }" + ""
						+ "            .es-footer-body p," + "            .es-footer-body ul li,"
						+ "            .es-footer-body ol li," + "            .es-footer-body a {"
						+ "                font-size: 16px" + "            }" + "" + "            .es-infoblock p,"
						+ "            .es-infoblock ul li," + "            .es-infoblock ol li,"
						+ "            .es-infoblock a {" + "                font-size: 12px" + "            }" + ""
						+ "            *[class=\"gmail-fix\"] {" + "                display: none" + "            }"
						+ "" + "            .es-m-txt-c," + "            .es-m-txt-c h1,"
						+ "            .es-m-txt-c h2," + "            .es-m-txt-c h3 {"
						+ "                text-align: center" + "            }" + "" + "            .es-m-txt-r,"
						+ "            .es-m-txt-r h1," + "            .es-m-txt-r h2," + "            .es-m-txt-r h3 {"
						+ "                text-align: right" + "            }" + "" + "            .es-m-txt-l,"
						+ "            .es-m-txt-l h1," + "            .es-m-txt-l h2," + "            .es-m-txt-l h3 {"
						+ "                text-align: left" + "            }" + "" + "            .es-m-txt-r img {"
						+ "                float: right" + "            }" + "" + "            .es-m-txt-c img {"
						+ "                margin: 0 auto" + "            }" + "" + "            .es-m-txt-l img {"
						+ "                float: left" + "            }" + "" + "            .es-button-border {"
						+ "                display: block" + "            }" + "" + "            a.es-button,"
						+ "            button.es-button {" + "                font-size: 20px;"
						+ "                display: block;" + "                border-width: 10px 0px 10px 0px"
						+ "            }" + "" + "            .es-btn-fw {" + "                border-width: 10px 0px;"
						+ "                text-align: center" + "            }" + ""
						+ "            .es-adaptive table," + "            .es-btn-fw," + "            .es-btn-fw-brdr,"
						+ "            .es-left," + "            .es-right {" + "                width: 100%"
						+ "            }" + "" + "            .es-content table," + "            .es-header table,"
						+ "            .es-footer table," + "            .es-content," + "            .es-footer,"
						+ "            .es-header {" + "                width: 100%;"
						+ "                max-width: 600px" + "            }" + "" + "            .es-adapt-td {"
						+ "                display: block;" + "                width: 100%" + "            }" + ""
						+ "            .adapt-img {" + "                width: 100%;" + "                height: auto"
						+ "            }" + "" + "            td.es-m-p0 {" + "                padding: 0px"
						+ "            }" + "" + "            td.es-m-p0r {" + "                padding-right: 0px"
						+ "            }" + "" + "            td.es-m-p0l {" + "                padding-left: 0px"
						+ "            }" + "" + "            td.es-m-p0t {" + "                padding-top: 0px"
						+ "            }" + "" + "            td.es-m-p0b {" + "                padding-bottom: 0"
						+ "            }" + "" + "            td.es-m-p20b {" + "                padding-bottom: 20px"
						+ "            }" + "" + "            .es-mobile-hidden," + "            .es-hidden {"
						+ "                display: none" + "            }" + "" + "            tr.es-desk-hidden,"
						+ "            td.es-desk-hidden," + "            table.es-desk-hidden {"
						+ "                width: auto;" + "                overflow: visible;"
						+ "                float: none;" + "                max-height: inherit;"
						+ "                line-height: inherit" + "            }" + ""
						+ "            tr.es-desk-hidden {" + "                display: table-row" + "            }"
						+ "" + "            table.es-desk-hidden {" + "                display: table" + "            }"
						+ "" + "            td.es-desk-menu-hidden {" + "                display: table-cell"
						+ "            }" + "" + "            .es-menu td {" + "                width: 1%"
						+ "            }" + "" + "            table.es-table-not-adapt,"
						+ "            .esd-block-html table {" + "                width: auto" + "            }" + ""
						+ "            table.es-social {" + "                display: inline-block" + "            }"
						+ "" + "            table.es-social td {" + "                display: inline-block"
						+ "            }" + "" + "            .es-desk-hidden {" + "                display: table-row;"
						+ "                width: auto;" + "                overflow: visible;"
						+ "                max-height: inherit" + "            }" + "        }" + "    </style>"
						+ "</head>" + "" + "<body ng-app=\"myApp\" ng-controller=\"myCtrl\">"
						+ "    <div class=\"es-wrapper-color\">"
						+ "        <!--[if gte mso 9]><v:background xmlns:v=\"urn:schemas-microsoft-com:vml\" fill=\"t\"> <v:fill type=\"tile\" color=\"#f6f6f6\"></v:fill> </v:background><![endif]-->"
						+ "        <table class=\"es-wrapper\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">"
						+ "            <tr>" + "                <td valign=\"top\">"
						+ "                    <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-content\" align=\"center\">"
						+ "                        <tr>"
						+ "                            <td class=\"es-adaptive\" align=\"center\">"
						+ "                                <table class=\"es-content-body\" style=\"background-color: transparent\" width=\"600\""
						+ "                                    cellspacing=\"0\" cellpadding=\"0\" align=\"center\">"
						+ "                                    <tr>"
						+ "                                        <td class=\"es-p10\" align=\"left\">"
						+ "                                            <!--[if mso]><table width=\"580\" cellpadding=\"0\" cellspacing=\"0\"><tr><td width=\"369\" valign=\"top\"><![endif]-->"
						+ "                                            <table class=\"es-left\" cellspacing=\"0\" cellpadding=\"0\" align=\"left\">"
						+ "                                                <tr>"
						+ "                                                    <td class=\"es-m-p0r es-m-p20b\" width=\"369\" valign=\"top\""
						+ "                                                        align=\"center\">"
						+ "                                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">"
						+ "                                                            <tr>"
						+ "                                                                <td align=\"center\" style=\"display: none\"></td>"
						+ "                                                            </tr>"
						+ "                                                        </table>"
						+ "                                                    </td>"
						+ "                                                </tr>"
						+ "                                            </table>"
						+ "                                            <!--[if mso]></td><td width=\"20\"></td><td width=\"191\" valign=\"top\"><![endif]-->"
						+ "                                            <table cellspacing=\"0\" cellpadding=\"0\" align=\"right\">"
						+ "                                                <tr>"
						+ "                                                    <td width=\"191\" align=\"left\">"
						+ "                                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">"
						+ "                                                            <tr>"
						+ "                                                                <td align=\"center\" style=\"display: none\"></td>"
						+ "                                                            </tr>"
						+ "                                                        </table>"
						+ "                                                    </td>"
						+ "                                                </tr>"
						+ "                                            </table> <!--[if mso]></td></tr></table><![endif]-->"
						+ "                                        </td>" + "                                    </tr>"
						+ "                                </table>" + "                            </td>"
						+ "                        </tr>" + "                    </table>"
						+ "                    <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-header\" align=\"center\">"
						+ "                        <tr>"
						+ "                            <td class=\"es-adaptive\" align=\"center\">"
						+ "                                <table class=\"es-header-body\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\""
						+ "                                    align=\"center\">"
						+ "                                    <tr>"
						+ "                                        <td class=\"es-p5t es-p5b\" align=\"left\">"
						+ "                                            <!--[if mso]><table width=\"600\" cellpadding=\"0\" cellspacing=\"0\"><tr><td width=\"184\" valign=\"top\"><![endif]-->"
						+ "                                            <table class=\"es-left\" cellspacing=\"0\" cellpadding=\"0\" align=\"left\">"
						+ "                                                <tr>"
						+ "                                                    <td class=\"es-m-p0r\" width=\"184\" valign=\"top\" align=\"center\">"
						+ "                                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\""
						+ "                                                            role=\"presentation\">"
						+ "                                                            <tr>"
						+ "                                                                <td class=\"es-m-p0l es-p10t es-p10b\" align=\"center\""
						+ "                                                                    style=\"font-size:0;\"><a"
						+ "                                                                      "
						+ "                                                                        target=\"_blank\"><img"
						+ "                                                                            src=\"https://media-cdn.tripadvisor.com/media/photo-s/0e/2a/64/0f/logo-gold-hotel.jpg\""
						+ "                                                                            alt=\"Smart travel logo\""
						+ "                                                                            title=\"Smart travel logo\" width=\"178\""
						+ "                                                                            height=\"41\"></a>"
						+ "                                                                                                              "
						+ "                                                                        </td>"
						+ "                                                            </tr>"
						+ "                                                        </table>"
						+ "                                                    </td>"
						+ "                                                </tr>"
						+ "                                            </table>"
						+ "                                            <!--[if mso]></td><td width=\"33\"></td><td width=\"383\" valign=\"top\"><![endif]-->"
						+ "                                            <table cellspacing=\"0\" cellpadding=\"0\" align=\"right\">"
						+ "                                                <tr>"
						+ "                                                    <td width=\"383\" align=\"left\">"
						+ "                                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\""
						+ "                                                            role=\"presentation\">"
						+ "                                                            <tr>"
						+ "                                                                <td>"
						+ "                                                                    <table class=\"es-menu\" width=\"100%\" cellspacing=\"0\""
						+ "                                                                        cellpadding=\"0\" role=\"presentation\">"
						+ "                                                                        <tr class=\"links\">"
						+ "                                                                            <td class=\"es-p10t es-p10b es-p5r es-p5l \""
						+ "                                                                                style=\"padding-bottom: 5px;padding-top: 23px\""
						+ "                                                                                width=\"33.33%\" bgcolor=\"transparent\""
						+ "                                                                                align=\"center\"><a target=\"_blank\""
						+ "                                                                                    style=\"color: #666666\""
						+ "                                                                                    href=\"tel:0342740374\">+84242740374</a>"
						+ "                                                                            </td>"
						+ "                                                                            <td class=\"es-p10t es-p10b es-p5r es-p5l \""
						+ "                                                                                style=\"padding-bottom: 5px;padding-top: 23px\""
						+ "                                                                                width=\"33.33%\" bgcolor=\"transparent\""
						+ "                                                                                align=\"center\"><a target=\"_blank\""
						+ "                                                                                    style=\"color: #666666\""
						+ "                                                                                    href=\"mailto:huannqps18946@fpt.edu.vn\">huannqps18946@fpt.edu.vn</a>"
						+ "                                                                            </td>" +

						"                                                                        </tr>"
						+ "                                                                    </table>"
						+ "                                                                </td>"
						+ "                                                            </tr>"
						+ "                                                        </table>"
						+ "                                                    </td>"
						+ "                                                </tr>"
						+ "                                            </table> <!--[if mso]></td></tr></table><![endif]-->"
						+ "                                        </td>" + "                                    </tr>"
						+ "                                </table>" + "                            </td>"
						+ "                        </tr>" + "                    </table>"
						+ "                    <table class=\"es-content\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">"
						+ "                        <tr>" + "                            <td align=\"center\">"
						+ "                                <table class=\"es-content-body\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\""
						+ "                                    bgcolor=\"#ffffff\" align=\"center\">"
						+ "                                    <tr>"
						+ "                                        <td align=\"left\">"
						+ "                                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">"
						+ "                                                <tr>"
						+ "                                                    <td width=\"600\" valign=\"top\" align=\"center\">"
						+ "                                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\""
						+ "                                                            role=\"presentation\">"
						+ "                                                            <tr>"
						+ "                                                                <td align=\"center\" style=\"font-size:0\"><img"
						+ "                                                                        src=\"https://ylizcr.stripocdn.email/content/guids/CABINET_7a17d17e0fd2296595b61c01d90dfaee/images/62771506321297100.jpg\""
						+ "                                                                        alt=\"Sea\" class=\"adapt-img\" title=\"Sea\""
						+ "                                                                        width=\"600\" height=\"301\""
						+ "                                                                        layout=\"responsive\"></td>"
						+ "                                                            </tr>"
						+ "                                                        </table>"
						+ "                                                    </td>"
						+ "                                                </tr>"
						+ "                                                <tr>"
						+ "                                                    <td width=\"600\" valign=\"top\" align=\"center\">"
						+ "                                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\""
						+ "                                                            role=\"presentation\">"
						+ "                                                            <tr>"
						+ "                                                                <td class=\"es-p10r es-p10l\" align=\"center\""
						+ "                                                                    style=\"font-size:0\"><h1 style=\"font-size: 45px; font-weight: 600; font-family: Verdana, Geneva, Tahoma, sans-serif;\">"
						+ title + "</h1></td>" + "                                                            </tr>"
						+ "                                                        </table>"
						+ "                                                    </td>"
						+ "                                                </tr>"
						+ "                                            </table>"
						+ "                                        </td>" + "                                    </tr>"
						+ "                                    <tr>"
						+ "                                        <td class=\"es-p20r es-p20l\" align=\"left\">"
						+ "                                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">"
						+ "                                                <tr>"
						+ "                                                    <td width=\"560\" valign=\"top\" align=\"center\">"
						+ "                                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\""
						+ "                                                            role=\"presentation\">"
						+ "                                                            <tr>"
						+ "                                                                <td class=\"es-p5t es-p10b\" align=\"center\">"
						+ "                                                                    <p>" + description
						+ "</p>" + "                                                                </td>"
						+ "                                                            </tr>"
						+ "                                                        </table>"
						+ "                                                    </td>"
						+ "                                                </tr>"
						+ "                                            </table>"
						+ "                                        </td>" + "                                    </tr>"
						+ "                                </table>" + "                            </td>"
						+ "                        </tr>" + "                    </table>"
						+ "                    <table class=\"es-content\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">"
						+ "                        <tr>" + "                            <td align=\"center\">"

						+ "                                                                   " +test
						+ "                                            "
						+ "                                        </td>" + "                                    </tr>"
						+ "                                    <tr>"
						+ "                                        <td class=\"es-p20t es-p30b es-p20r es-p20l\" align=\"left\">"
						+ "                                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">"
						+ "                                                <tr>"
						+ "                                                    <td width=\"560\" valign=\"top\" align=\"center\">"
						+ "                                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\""
						+ "                                                            role=\"presentation\">"
						+ "                                                            <tr>"
						+ "                                                                <td align=\"center\">"
						+ "                                                                    <h2><span style=\"color: #faa41d\">CALL NOW:</span>"
						+ "                                                                        0342740374</h2>"
						+ "                                                                </td>"
						+ "                                                            </tr>"
						+ "                                                        </table>"
						+ "                                                    </td>"
						+ "                                                </tr>"
						+ "                                            </table>"
						+ "                                        </td>" + "                                    </tr>"
						+ "                                </table>" + "                            </td>"
						+ "                        </tr>" + "                    </table>"
						+ "                    <table class=\"es-content\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">"
						+ "                        <tr>" + "                            <td align=\"center\">"
						+ "                                <table class=\"es-content-body\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\""
						+ "                                    bgcolor=\"#ffffff\" align=\"center\">"
						+ "                                    <tr>"
						+ "                                        <td class=\"es-p10\" align=\"left\">"
						+ "                                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">"
						+ "                                                <tr>"
						+ "                                                    <td width=\"580\" valign=\"top\" align=\"center\">"
						+ "                                                        <table"
						+ "                                                            style=\"border-collapse: separate;border-width: 0px;border-style: solid;border-color: #ffffff #ffffff\""
						+ "                                                            width=\"100%\" cellspacing=\"0\" cellpadding=\"0\""
						+ "                                                            role=\"presentation\">"
						+ "                                                            <tr>"
						+ "                                                                <td class=\"es-p10r es-p10l\" align=\"center\""
						+ "                                                                    style=\"font-size:0\"><img"
						+ "                                                                        src=\"https://ylizcr.stripocdn.email/content/guids/CABINET_f0b624206fab57852ad3180484ef1b2f/images/63901506327452749.jpg\""
						+ "                                                                        alt=\"Our recommendations\" class=\"adapt-img\""
						+ "                                                                        title=\"Our recommendations\" width=\"370\""
						+ "                                                                        height=\"41\" layout=\"responsive\"></td>"
						+ "                                                            </tr>"
						+ "                                                            <tr>"
						+ "                                                                <td class=\"es-p5t es-p10b\" align=\"center\">"
						+ "                                                                    <p>We found the most beautiful places and great"
						+ "                                                                        deals for you.</p>"
						+ "                                                                </td>"
						+ "                                                            </tr>"
						+ "                                                        </table>"
						+ "                                                    </td>"
						+ "                                                </tr>"
						+ "                                            </table>"
						+ "                                        </td>" + "                                    </tr>"
						+ "                                    <tr>"
						+ "                                        <td class=\"es-p10t es-p20r es-p20l\" align=\"left\">"
						+ "                                            <!--[if mso]><table width=\"560\" cellpadding=\"0\" cellspacing=\"0\"><tr><td width=\"178\" valign=\"top\"><![endif]-->"
						+ "                                            <table class=\"es-left\" cellspacing=\"0\" cellpadding=\"0\" align=\"left\">"
						+ "                                                <tr>"
						+ "                                                    <td class=\"es-m-p0r es-m-p20b\" width=\"178\" valign=\"top\""
						+ "                                                        align=\"center\">"
						+ "                                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\""
						+ "                                                            role=\"presentation\">"
						+ "                                                            <tr>"
						+ "                                                                <td align=\"center\">"
						+ "                                                                    <h3>Orlando, Florida</h3>"
						+ "                                                                </td>"
						+ "                                                            </tr>"
						+ "                                                            <tr>"
						+ "                                                                <td class=\"es-p10t es-p10b\" align=\"center\">"
						+ "                                                                    <p style=\"line-height: 18px;font-size: 12px\">Orlando"
						+ "                                                                        is a city in the U.S. state of Florida and the"
						+ "                                                                        county seat of Orange County.<br></p>"
						+ "                                                                </td>"
						+ "                                                            </tr>"
						+ "                                                            <tr>"
						+ "                                                                <td align=\"center\" style=\"font-size:0\"><img"
						+ "                                                                        class=\"adapt-img\""
						+ "                                                                        src=\"https://ylizcr.stripocdn.email/content/guids/CABINET_f5a54491d786eb74fd5d02f051902d39/images/65681506324211732.jpg\""
						+ "                                                                        alt=\"Orlando\" title=\"Orlando\" width=\"178\""
						+ "                                                                        height=\"119\" layout=\"responsive\"></td>"
						+ "                                                            </tr>"
						+ "                                                        </table>"
						+ "                                                    </td>"
						+ "                                                </tr>"
						+ "                                            </table>"
						+ "                                            <!--[if mso]></td><td width=\"20\"></td><td width=\"362\" valign=\"top\"><![endif]-->"
						+ "                                            <table cellspacing=\"0\" cellpadding=\"0\" align=\"right\">"
						+ "                                                <tr>"
						+ "                                                    <td width=\"362\" align=\"left\">"
						+ "                                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\""
						+ "                                                            role=\"presentation\">"
						+ "                                                            <tr>"
						+ "                                                                <td class=\"es-p10t\" align=\"center\" style=\"font-size:0\">"
						+ "                                                                    <img class=\"adapt-img\""
						+ "                                                                        src=\"https://ylizcr.stripocdn.email/content/guids/CABINET_f5a54491d786eb74fd5d02f051902d39/images/98321506324206971.jpg\""
						+ "                                                                        alt=\"Orlando Walt Disney World\""
						+ "                                                                        title=\"Orlando Walt Disney World\" width=\"362\""
						+ "                                                                        height=\"211\" layout=\"responsive\"></td>"
						+ "                                                            </tr>"
						+ "                                                        </table>"
						+ "                                                    </td>"
						+ "                                                </tr>"
						+ "                                            </table> <!--[if mso]></td>"
						+ "</tr></table><![endif]-->" + "                                        </td>"
						+ "                                    </tr>" + "                                    <tr>"
						+ "                                        <td class=\"es-p20t es-p10b es-p20r es-p20l\" align=\"left\">"
						+ "                                            <!--[if mso]><table width=\"560\" cellpadding=\"0\" cellspacing=\"0\"><tr><td width=\"270\" valign=\"top\"><![endif]-->"
						+ "                                            <table class=\"es-left\" cellspacing=\"0\" cellpadding=\"0\" align=\"left\">"
						+ "                                                <tr>"
						+ "                                                    <td class=\"es-m-p20b\" width=\"270\" align=\"left\">"
						+ "                                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\""
						+ "                                                            role=\"presentation\">"
						+ "                                                            <tr>"
						+ "                                                                <td align=\"center\" style=\"font-size:0\"><img"
						+ "                                                                        class=\"adapt-img\""
						+ "                                                                        src=\"https://ylizcr.stripocdn.email/content/guids/CABINET_f5a54491d786eb74fd5d02f051902d39/images/81491506324632163.jpg\""
						+ "                                                                        alt=\"Orlando Walt Disney World\""
						+ "                                                                        title=\"Orlando Walt Disney World\" width=\"270\""
						+ "                                                                        height=\"180\" layout=\"responsive\"></td>"
						+ "                                                            </tr>"
						+ "                                                        </table>"
						+ "                                                    </td>"
						+ "                                                </tr>"
						+ "                                            </table> <!--[if mso]></td><td width=\"20\"></td>"
						+ "<td width=\"270\" valign=\"top\"><![endif]-->"
						+ "                                            <table class=\"es-right\" cellspacing=\"0\" cellpadding=\"0\" align=\"right\">"
						+ "                                                <tr>"
						+ "                                                    <td width=\"270\" align=\"left\">"
						+ "                                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\""
						+ "                                                            role=\"presentation\">"
						+ "                                                            <tr>"
						+ "                                                                <td align=\"center\" style=\"font-size:0\"><img"
						+ "                                                                        class=\"adapt-img\""
						+ "                                                                        src=\"https://ylizcr.stripocdn.email/content/guids/CABINET_f5a54491d786eb74fd5d02f051902d39/images/59681506325024428.jpg\""
						+ "                                                                        alt=\"Orlando's famous attractions\""
						+ "                                                                        title=\"Orlando's famous attractions\" width=\"270\""
						+ "                                                                        height=\"180\" layout=\"responsive\"></td>"
						+ "                                                            </tr>"
						+ "                                                        </table>"
						+ "                                                    </td>"
						+ "                                                </tr>"
						+ "                                            </table> <!--[if mso]></td></tr></table><![endif]-->"
						+ "                                        </td>" + "                                    </tr>"
						+ "                                    <tr>"
						+ "                                        <td class=\"es-p5t es-p20b es-p20r es-p20l\" align=\"left\">"
						+ "                                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">"
						+ "                                                <tr>"
						+ "                                                    <td width=\"560\" valign=\"top\" align=\"center\">"
						+ "                                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\""
						+ "                                                            role=\"presentation\">"
						+ "                                                            <tr>"
						+ "                                                                <td align=\"center\">"
						+ "                                                                    <p style=\"line-height: 150%\">As one of the world's"
						+ "                                                                        most visited tourist destinations, Orlando's"
						+ "                                                                        famous attractions form the backbone of its"
						+ "                                                                        tourism industry: Walt Disney World, the"
						+ "                                                                        Universal Orlando Resort. With the exception of"
						+ "                                                                        Walt Disney World, most major attractions are"
						+ "                                                                        located along International Drive.</p>"
						+ "                                                                </td>"
						+ "                                                            </tr>"
						+ "                                                            <tr>"
						+ "                                                                <td>"
						+ "                                                                    <table class=\"es-menu\" width=\"100%\" cellspacing=\"0\""
						+ "                                                                        cellpadding=\"0\" role=\"presentation\">"
						+ "                                                                        <tr class=\"links-images-right\">"
						+ "                                                                            <td class=\"es-p10t es-p10b es-p5r es-p5l\""
						+ "                                                                                style=\"padding-bottom: 10px;padding-top: 10px\""
						+ "                                                                                id=\"esd-menu-id-0\" width=\"100.00%\""
						+ "                                                                                bgcolor=\"transparent\" align=\"center\"><a"
						+ "                                                                                    style=\"color: #faa41d\""
						+ "                                                                                    href=\"https://viewstripo.email/\">Read"
						+ "                                                                                    more<img"
						+ "                                                                                        src=\"https://ylizcr.stripocdn.email/content/guids/CABINET_f994733da32bd87854783df94a602de9/images/94081505906718107.png\""
						+ "                                                                                        alt=\"Read more\""
						+ "                                                                                        title=\"Read more\" width=\"16\""
						+ "                                                                                        height=\"13\""
						+ "                                                                                        style=\"margin-left:5px\"></a>"
						+ "                                                                            </td>"
						+ "                                                                        </tr>"
						+ "                                                                    </table>"
						+ "                                                                </td>"
						+ "                                                            </tr>"
						+ "                                                        </table>"
						+ "                                                    </td>"
						+ "                                                </tr>"
						+ "                                            </table>"
						+ "                                        </td>" + "                                    </tr>"
						+ "                                </table>" + "                            </td>"
						+ "                        </tr>" + "                    </table>"
						+ "                    <table class=\"es-content\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">"
						+ "                        <tr>" + "                            <td align=\"center\">"
						+ "                                <table class=\"es-content-body\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\""
						+ "                                    bgcolor=\"#ffffff\" align=\"center\">"
						+ "                                    <tr>"
						+ "                                        <td align=\"left\">"
						+ "                                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">"
						+ "                                                <tr>"
						+ "                                                    <td width=\"600\" valign=\"top\" align=\"center\">"
						+ "                                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\""
						+ "                                                            role=\"presentation\">"
						+ "                                                            <tr>"
						+ "                                                                <td align=\"center\" style=\"font-size:0\"><img"
						+ "                                                                        src=\"https://ylizcr.stripocdn.email/content/guids/CABINET_f5a54491d786eb74fd5d02f051902d39/images/99501506005983262.jpg\""
						+ "                                                                        alt=\"Sea\" class=\"adapt-img\" title=\"Sea\""
						+ "                                                                        width=\"600\" height=\"260\""
						+ "                                                                        layout=\"responsive\"></td>"
						+ "                                                            </tr>"
						+ "                                                        </table>"
						+ "                                                    </td>"
						+ "                                                </tr>"
						+ "                                            </table>"
						+ "                                        </td>" + "                                    </tr>"
						+ "                                </table>" + "                            </td>"
						+ "                        </tr>" + "                    </table>"
						+ "                    <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-footer\" align=\"center\">"
						+ "                        <tr>" + "                            <td align=\"center\">"
						+ "                                <table class=\"es-footer-body\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\""
						+ "                                    align=\"center\">"
						+ "                                    <tr>"
						+ "                                        <td class=\"es-p20\" align=\"left\">"
						+ "                                            <!--[if mso]><table width=\"560\" cellpadding=\"0\" cellspacing=\"0\"><tr><td width=\"356\" valign=\"top\"><![endif]-->"
						+ "                                            <table class=\"es-left\" cellspacing=\"0\" cellpadding=\"0\" align=\"left\">"
						+ "                                                <tr>"
						+ "                                                    <td class=\"es-m-p20b\" width=\"356\" align=\"left\">"
						+ "                                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\""
						+ "                                                            role=\"presentation\">"
						+ "                                                            <tr>"
						+ "                                                                <td align=\"left\">"
						+ "                                                                    <p style=\"line-height: 200%\">© 2022 Golden Hotel. All"
						+ "                                                                        rights reserved.</p>"
						+ "                                                                    <p style=\"line-height: 200%\">You're receiving this"
						+ "                                                                        email because you subscribed our site.</p>"
						+ "                                                                    <p style=\"line-height: 200%\"><a target=\"_blank\""
						+ "                                                                            class=\"unsubscribe\" href>Unsubscribe</a></p>"
						+ "                                                                </td>"
						+ "                                                            </tr>"
						+ "                                                        </table>"
						+ "                                                    </td>"
						+ "                                                </tr>"
						+ "                                            </table> <!--[if mso]></td><td width=\"20\"></td>"
						+ "<td width=\"184\" valign=\"top\"><![endif]-->"
						+ "                                            <table cellspacing=\"0\" cellpadding=\"0\" align=\"right\">"
						+ "                                                <tr>"
						+ "                                                    <td width=\"184\" align=\"left\">"
						+ "                                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\""
						+ "                                                            role=\"presentation\">"
						+ "                                                            <tr>"
						+ "                                                                <td align=\"left\">"
						+ "                                                                    <p style=\"line-height: 200%\"><a target=\"_blank\""
						+ "                                                                            href=\"\">Questions?</a>"
						+ "                                                                    </p>"
						+ "                                                                    <p style=\"line-height: 200%\"><a target=\"_blank\""
						+ "                                                                            href=\"\">Email us</a>"
						+ "                                                                    </p>"
						+ "                                                                    <p style=\"line-height: 200%\"><a target=\"_blank\""
						+ "                                                                            style=\"line-height: 200%\""
						+ "                                                                            href=\"tel:0342740374\">0342740374</a></p>"
						+ "                                                                </td>"
						+ "                                                            </tr>"
						+ "                                                            <tr>"
						+ "                                                                <td class=\"es-p5t\" align=\"left\" style=\"font-size:0\">"
						+ "                                                                    <table class=\"es-table-not-adapt es-social\""
						+ "                                                                        cellspacing=\"0\" cellpadding=\"0\""
						+ "                                                                        role=\"presentation\">"
						+ "                                                                        <tr>"
						+ "                                                                            <td class=\"es-p10r\" valign=\"top\""
						+ "                                                                                align=\"center\"><img title=\"Twitter\""
						+ "                                                                                    src=\"https://ylizcr.stripocdn.email/content/assets/img/social-icons/rounded-gray/twitter-rounded-gray.png\""
						+ "                                                                                    alt=\"Tw\" width=\"24\""
						+ "                                                                                    height=\"24\"></td>"
						+ "                                                                            <td class=\"es-p10r\" valign=\"top\""
						+ "                                                                                align=\"center\"><img title=\"Facebook\""
						+ "                                                                                    src=\"https://ylizcr.stripocdn.email/content/assets/img/social-icons/rounded-gray/facebook-rounded-gray.png\""
						+ "                                                                                    alt=\"Fb\" width=\"24\""
						+ "                                                                                    height=\"24\"></td>"
						+ "                                                                            <td class=\"es-p10r\" valign=\"top\""
						+ "                                                                                align=\"center\"><img title=\"Youtube\""
						+ "                                                                                    src=\"https://ylizcr.stripocdn.email/content/assets/img/social-icons/rounded-gray/youtube-rounded-gray.png\""
						+ "                                                                                    alt=\"Yt\" width=\"24\""
						+ "                                                                                    height=\"24\"></td>"
						+ "                                                                            <td valign=\"top\" align=\"center\"><img"
						+ "                                                                                    title=\"Vkontakte\""
						+ "                                                                                    src=\"https://ylizcr.stripocdn.email/content/assets/img/social-icons/rounded-gray/vk-rounded-gray.png\""
						+ "                                                                                    alt=\"Vk\" width=\"24\""
						+ "                                                                                    height=\"24\"></td>"
						+ "                                                                        </tr>"
						+ "                                                                    </table>"
						+ "                                                                </td>"
						+ "                                                            </tr>"
						+ "                                                        </table>"
						+ "                                                    </td>"
						+ "                                                </tr>"
						+ "                                            </table> <!--[if mso]></td></tr></table><![endif]-->"
						+ "                                        </td>" + "                                    </tr>"
						+ "                                </table>" + "                            </td>"
						+ "                        </tr>" + "                    </table>"
						+ "                    <table class=\"es-content\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">"
						+ "                        <tr>" + "                            <td align=\"center\">"
						+ "                                <table class=\"es-content-body\" style=\"background-color: transparent\" width=\"600\""
						+ "                                    cellspacing=\"0\" cellpadding=\"0\" align=\"center\">"
						+ "                                    <tr>"
						+ "                                        <td class=\"es-p30t es-p30b es-p20r es-p20l\" align=\"left\">"
						+ "                                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">"
						+ "                                                <tr>"
						+ "                                                    <td width=\"560\" valign=\"top\" align=\"center\">"
						+ "                                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">"
						+ "                                                            <tr>"
						+ "                                                                <td align=\"center\" style=\"display: none\"></td>"
						+ "                                                            </tr>"
						+ "                                                        </table>"
						+ "                                                    </td>"
						+ "                                                </tr>"
						+ "                                            </table>"
						+ "                                        </td>" + "                                    </tr>"
						+ "                                </table>" + "                            </td>"
						+ "                        </tr>" + "                    </table>" + "                </td>"
						+ "            </tr>" + "        </table>" + "    </div>" + "</body>  " + "</html>"

				);

			} catch (Exception e) {
				e.printStackTrace();
			}
		}

		return "redirect:/admin/index.html#!/guest-manager";
	}

}
